version: '3'
networks:
 dev_planestic:

services:
  ud-repository-client:
      image: planesticud/ud-repository-client
     container_name: ud-repository-client
     restart: on-failure
     env_file:
        - .env
     networks:
        - dev_planestic
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ud-repository-client.rule=Host(`rdigital.planestic.udistrital.edu.co`)"
      - "traefik.http.routers.ud-repository-client.tls=true"
      - "traefik.http.routers.ud-repository-client.tls.certresolver=le"
      - "traefik.http.services.ud-repository-client.loadbalancer.server.port=80"           
networks:
  dev_planestic:
    external: true
