version: '3'
networks:
 udrepository:

services:
  ud-repository-client:
     image: damillano93/ud-repository-client
     container_name: ud-repository-client
     restart: on-failure
     env_file:
        - .env
     networks:
        - udrepository
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ud-repository-client.rule=Host(`udrepository.com`)"
      #- "traefik.http.routers.ud-repository-client.tls=true"
      #- "traefik.http.routers.ud-repository-client.tls.certresolver=le"
      - "traefik.http.services.ud-repository-client.loadbalancer.server.port=80"           
networks:
  udrepository:
    external: true
